name: Run TestRigor Tests

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test-rigor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run TestRigor Test
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            -H 'auth-token: 420e37b3-7802-470e-abd9-dc62c604bad1' \
            --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
            https://api.testrigor.com/api/v1/apps/AQquPrnD3xEuQdTT7/retest

          sleep 10

          while true
          do
            echo " "
            echo "==================================="
            echo " Checking TestRigor retest"
            echo "==================================="
            response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/AQquPrnD3xEuQdTT7/status' -H 'auth-token: 420e37b3-7802-470e-abd9-dc62c604bad1' -H 'Accept: application/json')
            code=$(echo "$response" | grep HTTP |  awk '{print $2}')
            body=$(echo "$response" | sed -n '/{/,/}/p')
            echo "Status code: " $code
            echo "Response: " $body
            case $code in
              4*|5*)
                echo "Error calling API"
                exit 1
                ;;
              200)
                echo "Test finished successfully"
                exit 0
                ;;
              227|228)
                echo "Test is not finished yet"
                ;;
              230)
                echo "Test finished but failed"
                exit 1
                ;;
              *)
                echo "Unknown status"
                exit 1
            esac
            sleep 10
          done
